keys:
  users: &users
    - &vipul age1wgsecequ5euu0nzc2s5haqpgvupnldk7r3lzvrmffhew0me3sctquknz95
    - &vipul_laptop age19su0np46dx6pxrvf35ntnzutanlag06cp8rzcejl7vu0h7hfpuasugalkq
  hosts: &hosts
    - &laptop age1ydng6kf7rqjk9765fkxpfv7fw54vtux942pvqt43s4jaa5qpyfdqn6225d
creation_rules:
  - path_regex: ^secrets/sops/shared\.yaml$
    key_groups:
      - age:
          - *vipul
          - *laptop
          - *vipul_laptop
  - path_regex: ^secrets/sops/vipul\.yaml$
    key_groups:
      - age:
          - *vipul
          - *vipul_laptop
  - path_regex: ^secrets/sops/laptop\.yaml$
    key_groups:
      - age:
          - *vipul
          - *laptop
  - path_regex: ^secrets/sops/vipul_laptop\.yaml$
    key_groups:
      - age:
          - *vipul
          - *vipul_laptop
