keys:
  users: &users
  hosts: &hosts
    - &igloo age1fh4tedu9k8ww6cekpgde3a739w8np8h2svrmqm2ng7we57tzs53q86uewe
    - &iceberg age1zt8r6v49hhpcd9yntspmtcpudnp64ug4spt8vff3xtuvjr7gxdaqkzuzlg
creation_rules:
  - path_regex: ^secrets/sops/shared\.yaml$
    key_groups:
      - age:
          - *igloo
          - *iceberg
  - path_regex: ^secrets/sops/igloo\.yaml$
    key_groups:
      - age:
          - *igloo
  - path_regex: ^secrets/sops/iceberg\.yaml$
    key_groups:
      - age:
          - *iceberg
